// Code generated by ogen, DO NOT EDIT.

package restapi

import (
	"net/http"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

// V1RequestReplyPostParams is parameters of POST /v1/request-reply operation.
type V1RequestReplyPostParams struct {
	// The ID of the request.
	XRequestID OptString `json:",omitempty,omitzero"`
	Subject    string
	// Timeout to wait reply (in Go duration). Default is the the server's default specified on its start.
	ReplyTimeout OptString `json:",omitempty,omitzero"`
}

func unpackV1RequestReplyPostParams(packed middleware.Parameters) (params V1RequestReplyPostParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-Request-Id",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.XRequestID = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "subject",
			In:   "query",
		}
		params.Subject = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "ReplyTimeout",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ReplyTimeout = v.(OptString)
		}
	}
	return params
}

func decodeV1RequestReplyPostParams(args [0]string, argsEscaped bool, r *http.Request) (params V1RequestReplyPostParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-Request-Id.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Request-Id",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotXRequestIDVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotXRequestIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.XRequestID.SetTo(paramsDotXRequestIDVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Request-Id",
			In:   "header",
			Err:  err,
		}
	}
	// Decode query: subject.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "subject",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Subject = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "subject",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: ReplyTimeout.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "ReplyTimeout",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotReplyTimeoutVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotReplyTimeoutVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ReplyTimeout.SetTo(paramsDotReplyTimeoutVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "ReplyTimeout",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
