// Code generated by ogen, DO NOT EDIT.

package restapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// V1RequestReplyPost implements POST /v1/request-reply operation.
	//
	// Use request-reply.
	//
	// POST /v1/request-reply
	V1RequestReplyPost(ctx context.Context, req *V1RequestReplyPostReqWithContentType, params V1RequestReplyPostParams) (V1RequestReplyPostRes, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
