// Code generated by ogen, DO NOT EDIT.

package restapi

// OperationName is the ogen operation name
type OperationName = string

const (
	V1RequestReplyPostOperation OperationName = "V1RequestReplyPost"
)
