// Code generated by ogen, DO NOT EDIT.

package restapi

import (
	"fmt"
	"io"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/Error
type Error struct {
	// Error description.
	Message string    `json:"message"`
	Title   OptString `json:"title"`
	Code    OptString `json:"code"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// GetTitle returns the value of Title.
func (s *Error) GetTitle() OptString {
	return s.Title
}

// GetCode returns the value of Code.
func (s *Error) GetCode() OptString {
	return s.Code
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// SetTitle sets the value of Title.
func (s *Error) SetTitle(val OptString) {
	s.Title = val
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val OptString) {
	s.Code = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// V1RequestReplyPostBadRequest is response for V1RequestReplyPost operation.
type V1RequestReplyPostBadRequest struct{}

func (*V1RequestReplyPostBadRequest) v1RequestReplyPostRes() {}

// NATS response.
type V1RequestReplyPostOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s V1RequestReplyPostOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// V1RequestReplyPostOKHeaders wraps V1RequestReplyPostOK with response headers.
type V1RequestReplyPostOKHeaders struct {
	ContentType string
	Rtt         string
	Response    V1RequestReplyPostOK
}

// GetContentType returns the value of ContentType.
func (s *V1RequestReplyPostOKHeaders) GetContentType() string {
	return s.ContentType
}

// GetRtt returns the value of Rtt.
func (s *V1RequestReplyPostOKHeaders) GetRtt() string {
	return s.Rtt
}

// GetResponse returns the value of Response.
func (s *V1RequestReplyPostOKHeaders) GetResponse() V1RequestReplyPostOK {
	return s.Response
}

// SetContentType sets the value of ContentType.
func (s *V1RequestReplyPostOKHeaders) SetContentType(val string) {
	s.ContentType = val
}

// SetRtt sets the value of Rtt.
func (s *V1RequestReplyPostOKHeaders) SetRtt(val string) {
	s.Rtt = val
}

// SetResponse sets the value of Response.
func (s *V1RequestReplyPostOKHeaders) SetResponse(val V1RequestReplyPostOK) {
	s.Response = val
}

func (*V1RequestReplyPostOKHeaders) v1RequestReplyPostRes() {}

type V1RequestReplyPostReq struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s V1RequestReplyPostReq) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// V1RequestReplyPostReqWithContentType wraps V1RequestReplyPostReq with Content-Type.
type V1RequestReplyPostReqWithContentType struct {
	ContentType string
	Content     V1RequestReplyPostReq
}

// GetContentType returns the value of ContentType.
func (s *V1RequestReplyPostReqWithContentType) GetContentType() string {
	return s.ContentType
}

// GetContent returns the value of Content.
func (s *V1RequestReplyPostReqWithContentType) GetContent() V1RequestReplyPostReq {
	return s.Content
}

// SetContentType sets the value of ContentType.
func (s *V1RequestReplyPostReqWithContentType) SetContentType(val string) {
	s.ContentType = val
}

// SetContent sets the value of Content.
func (s *V1RequestReplyPostReqWithContentType) SetContent(val V1RequestReplyPostReq) {
	s.Content = val
}
