// Code generated by ogen, DO NOT EDIT.

package restapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// V1RequestReplyPost implements POST /v1/request-reply operation.
//
// Use request-reply.
//
// POST /v1/request-reply
func (UnimplementedHandler) V1RequestReplyPost(ctx context.Context, req *V1RequestReplyPostReqWithContentType, params V1RequestReplyPostParams) (r V1RequestReplyPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
